language: php

php:
  - 7.0

before_script:
- cp .env.travis .env
- mysql -e 'create database homestead;'
- travis_retry composer self-update
- composer install --prefer-source --no-interaction --dev
- php artisan key:generate
- php artisan migrate --seed

script: vendor/bin/phpunit
